### ISSUE TITLE
Community/People Map

### ISSUE THREAD

**Issue by nelsonic** [dwyl/stars#20]
The idea behind collecting the list of people's _profiles_ was to plot the community on a map.
Example:
![image](https://user-images.githubusercontent.com/194400/28494276-2c0a5e1a-6f21-11e7-8b5d-8bed3e17eb87.png)
see: https://minio.io (_scroll down_)

# Todo:
+ [ ] Loop through the list of people's profiles: https://github.com/dwyl/stars/tree/master/data/people
+ [ ] Create a list of the people who _have_ a `location` on their profile e.g: 
https://github.com/dwyl/stars/blob/96ede4d55f020e06d3a1edb488f3bad6840c58da/data/people/nelsonic.json#L30
+ [ ] GeoCode the location using GeoNames e.g: https://github.com/numo-labs/lambda-taggable-geonames-indexer (_here's one I made earlier_)
+ [ ] Plot the LatLon coordinates on a Google/OpenStreet Map.
+ [ ] include on dwyl's website 🎉
