### ISSUE TITLE
[Epic] What is (still) Required to Ship this?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/stars#6]
Things to be added:
+ [ ] (static) home page view explaining of purpose of the project and link to GitHub page
+ [ ] display list of repositories
+ [ ] ask people what _question_ they would _like_ to be able to answer about stars
+ [ ] add contributing.md to repo with link to https://github.com/dwyl/contributing
+ [ ] lint using `goodparts`: https://github.com/dwyl/goodparts/
+ [ ] add pre-commit hook to check coverage and lint ⬆️ 
+ [ ] add performance test(s) to measure how long page takes to re-load
+ [ ] cache views as necessary for fastest page load time
+ [ ] create subdomain or route on http://www.dwyl.io/ ...? (`help wanted`!)
+ [ ] allow people to login using their GitHub account and track their own repositories
+ [ ] receive alerts when new people :star: your project/content
+ [ ] manage frequency of alerts e.g: all-in-realtime vs. summary once per day
+ [ ] analytics
  + [ ] browser/device stats
  + [ ] which views are popular
  + [ ] count clicks on GitHub link
+ [ ] run main "spider" on Mac Mini @dwylHQ plugged into the "stats monitor"
+ [ ] heroku build pack to let ***other people*** deploy this to heroku with a single click?
+ [ ] deploy main app to DigitalOcean with CloudFlare acceleration?
+ [ ] _paid_ (SAAS) version to help companies with an Open Source "Program" track their GitHub? 
or keep it ***free***? (`discuss`!)

![boom](http://i.giphy.com/d0NnEG1WnnXqg.gif)
